### ISSUE TITLE
Enhance HTML table by filtering, sorting, etc.

### ISSUE THREAD

**Issue by mstoerzel** [Exirel/pylint-json2html#8]
Hi there,

great job. I'd like to contribute by adding some spice: enhance the HTML tables by jQuery based functionality to filter, sort, browse pagewise etc. 

If you grant me permission to commit I can push it upstream.

Cheers,

Marc
![Screenshot from 2020-07-10 16-46-03](https://user-images.githubusercontent.com/33293500/87161262-f18eb580-c2cc-11ea-9a14-aa517ba828ad.png)

**Comment by Exirel** [comment]
Hi, sorry for taking so long to reply (2020 was... something!).

First, if I were to accept such improvement (which looks pretty cool I have to say), I would not allow you to commit directly to this repository: you would have to fork it first.

Second, I won't accept this change, because I don't want to add more than it is necessary to the project. If someone wants to craft a better HTML template, they are free to do so, and to publish that in a separate repo.

Thanks for your contribution, it looks awesome, but I'll keep the project very basic.
